title: HUTMANN
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Andreas Hutmann
avatar: /logo.png
email: ro0330@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Hutmann
  card: summary
logo: logo.png
social:
  name: Andreas Hutmann
  links:
    - https://www.instagram.com/hyeon_1998_?igsh=aHBiNW5pcDF2ZWNy&utm_source=qr
    - https://andreashutmann.github.io/hutmann.github.io/about/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
